apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-test
  template:
    metadata:
      labels:
        app: vote-test
    spec:
      containers:
      - name: vote
        image: dogsvscats/vote:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "dummy-redis"  # Just for container startup test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-test
  template:
    metadata:
      labels:
        app: result-test
    spec:
      containers:
      - name: result
        image: dogsvscats/result:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "dummy-redis"  # Just for container startup test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-test
  template:
    metadata:
      labels:
        app: worker-test
    spec:
      containers:
      - name: worker
        image: dogsvscats/worker:latest
        env:
        - name: REDIS_HOST
          value: "dummy-redis"  # Just for container startup test